### ISSUE TITLE
Module directory name not suitable for Prestashop module uploader

### ISSUE THREAD

**Issue by TomAbel** [sendsmaily/smaily-prestashop-module#13]
The uploader works if the folder name (`smailyforprestashop`) and module file (`smailyforprestashop.php`) match.
Currently, the release folder is named `smaily-prestashop-module-#.#.#` and the module cannot be uploaded to a Prestashop shop using its built-in module uploader.

**Comment by kaittodesk** [comment]
Can we solve it with GitHub Actions? Similarly to OpenCart release bundling - https://github.com/sendsmaily/smaily-opencart-module/blob/1.5.x/.github/workflows/release.yaml
