### ISSUE TITLE
Option to trigger Smaily opt-in when customer joins with newsletter subscribers

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-prestashop-module#32]
**Describe the solution you'd like**
User should have the option to enable triggering Smaily opt-in when customer decides to join with newsletter subscribers. The option should be disabled by default. It is worth mentioning that opt-in should be triggered only when customer joins through sign-up (either through checkout or registration), and not when user changes customer's newsletter preference. User should be able to choose which automation opt-in triggers.

Opt-in request can be sent to Smaily using Autoresponders API endpoint - http://help.smaily.com/en/support/solutions/articles/16000021289-autoresponder.

EDIT: corrected phrasing.

**Comment by kaittodesk** [comment]
@TomAbel, this issue can be marked as resolved, I think.

**Comment by TomAbel** [comment]
Closed by #35 aswell
