### ISSUE TITLE
Rework logging

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-prestashop-module#36]
Current version of the module has an internal function for logging errors/information to a file in the modules directory. This can be a security risk as module files can be publicly accessible.

**Describe the solution you'd like**
Logging should be reworked to use PrestaShop built-in logging feature. This way developers that are debugging any possible issues with the module wouldn't need to know where to look for the logs.

**Comment by TomAbel** [comment]
closed by 38
