### ISSUE TITLE
PrestaShop 1.7.7 compatibility

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-prestashop-module#37]
PrestaShop 1.7.7.0RC1 has been released - https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-rc.1

We should test and make sure the module is compatible with the version and there aren't any issues.

**Comment by TomAbel** [comment]
Didn't find any issues. I upgraded Prestashop from 1.7.6 to 1.7.7.0RC1

**Comment by kaittodesk** [comment]
OK, looks like the module is compatible with PrestaShop 1.7.7. Closing task.
